version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx.app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5173:80
    extra_hosts:
      - "host.docker.internal:host-gateway"